// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSofqFlIF5SvZ9qFnLNupSm7NjOiFoVlk',
    appId: '1:309022852758:web:c632b2ff4c9d6f88ab64b7',
    messagingSenderId: '309022852758',
    projectId: 'jalvis-diary',
    authDomain: 'jalvis-diary.firebaseapp.com',
    storageBucket: 'jalvis-diary.firebasestorage.app',
    measurementId: 'G-90C65L2G1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6lnMOqzkhyZybnzHgI6xQX6FAxgCeM4',
    appId: '1:309022852758:android:64571f2e102dfd5cab64b7',
    messagingSenderId: '309022852758',
    projectId: 'jalvis-diary',
    storageBucket: 'jalvis-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1G1lJKmIbksjkrKwl5MzdGBSbD7dG6E',
    appId: '1:309022852758:ios:ed5b2696a587c760ab64b7',
    messagingSenderId: '309022852758',
    projectId: 'jalvis-diary',
    storageBucket: 'jalvis-diary.firebasestorage.app',
    iosBundleId: 'com.example.osswJalvis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw1G1lJKmIbksjkrKwl5MzdGBSbD7dG6E',
    appId: '1:309022852758:ios:ed5b2696a587c760ab64b7',
    messagingSenderId: '309022852758',
    projectId: 'jalvis-diary',
    storageBucket: 'jalvis-diary.firebasestorage.app',
    iosBundleId: 'com.example.osswJalvis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSofqFlIF5SvZ9qFnLNupSm7NjOiFoVlk',
    appId: '1:309022852758:web:2d439a69e30ea936ab64b7',
    messagingSenderId: '309022852758',
    projectId: 'jalvis-diary',
    authDomain: 'jalvis-diary.firebaseapp.com',
    storageBucket: 'jalvis-diary.firebasestorage.app',
    measurementId: 'G-LKD4K217WG',
  );
}
